sudo: false
notifications:
  email: false

language: python
python:
  -  "2.7"
env:
  - DJANGO_VERSION=1.8.0
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q djangorestframework==3.1.1
  - pip install nose
script:
  - nosetests --tests=CssefServer